import { 
  MenuItem, 
  MenuCategory, 
  Table, 
  Order,
  User,
  TableStatus,
  OrderStatus,
  OrderItemStatus,
  MenuItemStatus,
  UserRole
} from '../types';

// ==================== CATEGORÍAS DEL MENÚ ====================

export const mockCategories: MenuCategory[] = [
  { id: '1', name: 'Entradas', description: 'Aperitivos y entradas', order: 1, icon: '🥗', isActive: true },
  { id: '2', name: 'Platos Fuertes', description: 'Platos principales', order: 2, icon: '🍖', isActive: true },
  { id: '3', name: 'Pastas', description: 'Pastas italianas', order: 3, icon: '🍝', isActive: true },
  { id: '4', name: 'Mariscos', description: 'Especialidades del mar', order: 4, icon: '🦐', isActive: true },
  { id: '5', name: 'Postres', description: 'Dulces tentaciones', order: 5, icon: '🍰', isActive: true },
  { id: '6', name: 'Bebidas', description: 'Bebidas refrescantes', order: 6, icon: '🍹', isActive: true },
  { id: '7', name: 'Vinos', description: 'Selección de vinos', order: 7, icon: '🍷', isActive: true },
  { id: '8', name: 'Cócteles', description: 'Cócteles especiales', order: 8, icon: '🍸', isActive: true },
];

// ==================== ITEMS DEL MENÚ ====================

export const mockMenuItems: MenuItem[] = [
  // Entradas
  {
    id: '1',
    name: 'Ensalada César',
    description: 'Lechuga romana, crutones, parmesano y aderezo César',
    category: 'Entradas',
    price: 185,
    image: '/images/menu/caesar-salad.jpg',
    status: 'available' as MenuItemStatus,
    preparationTime: 10,
    destination: 'kitchen',
    allergens: ['gluten', 'lácteos', 'huevo'],
    isVegetarian: true,
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Camarones al Ajillo',
    description: 'Camarones salteados en aceite de oliva, ajo y vino blanco',
    category: 'Entradas',
    price: 245,
    status: 'available' as MenuItemStatus,
    preparationTime: 15,
    destination: 'kitchen',
    allergens: ['mariscos', 'ajo'],
    isPopular: true,
    isSpicy: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Bruschetta',
    description: 'Pan tostado con tomate fresco, albahaca y aceite de oliva',
    category: 'Entradas',
    price: 125,
    status: 'available' as MenuItemStatus,
    preparationTime: 8,
    destination: 'kitchen',
    allergens: ['gluten'],
    isVegetarian: true,
    isVegan: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  
  // Platos Fuertes
  {
    id: '4',
    name: 'Filete Mignon',
    description: 'Filete de res premium 250g con guarnición',
    category: 'Platos Fuertes',
    price: 485,
    status: 'available' as MenuItemStatus,
    preparationTime: 25,
    destination: 'kitchen',
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '5',
    name: 'Pollo a la Parmesana',
    description: 'Pechuga de pollo empanizada con salsa marinara y queso',
    category: 'Platos Fuertes',
    price: 285,
    status: 'available' as MenuItemStatus,
    preparationTime: 22,
    destination: 'kitchen',
    allergens: ['gluten', 'lácteos'],
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '6',
    name: 'Salmón a la Parrilla',
    description: 'Filete de salmón con vegetales asados',
    category: 'Platos Fuertes',
    price: 395,
    status: 'available' as MenuItemStatus,
    preparationTime: 20,
    destination: 'kitchen',
    allergens: ['pescado'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },

  // Pastas
  {
    id: '7',
    name: 'Fettuccine Alfredo',
    description: 'Pasta fresca con salsa cremosa de parmesano',
    category: 'Pastas',
    price: 235,
    status: 'available' as MenuItemStatus,
    preparationTime: 18,
    destination: 'kitchen',
    allergens: ['gluten', 'lácteos'],
    isVegetarian: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '8',
    name: 'Lasagna Bolognesa',
    description: 'Lasagna con carne molida y quesos',
    category: 'Pastas',
    price: 275,
    status: 'available' as MenuItemStatus,
    preparationTime: 25,
    destination: 'kitchen',
    allergens: ['gluten', 'lácteos'],
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },

  // Bebidas
  {
    id: '9',
    name: 'Margarita Clásica',
    description: 'Tequila, triple sec y limón',
    category: 'Cócteles',
    price: 135,
    status: 'available' as MenuItemStatus,
    preparationTime: 5,
    destination: 'bar',
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '10',
    name: 'Mojito',
    description: 'Ron blanco, menta, limón y soda',
    category: 'Cócteles',
    price: 125,
    status: 'available' as MenuItemStatus,
    preparationTime: 5,
    destination: 'bar',
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '11',
    name: 'Cerveza Corona',
    description: 'Cerveza importada 355ml',
    category: 'Bebidas',
    price: 65,
    status: 'available' as MenuItemStatus,
    preparationTime: 2,
    destination: 'bar',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },

  // Postres
  {
    id: '12',
    name: 'Tiramisú',
    description: 'Postre italiano con café y mascarpone',
    category: 'Postres',
    price: 145,
    status: 'available' as MenuItemStatus,
    preparationTime: 5,
    destination: 'kitchen',
    allergens: ['gluten', 'lácteos', 'huevo', 'alcohol'],
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '13',
    name: 'Cheesecake de Fresa',
    description: 'Tarta de queso con coulis de fresa',
    category: 'Postres',
    price: 135,
    status: 'available' as MenuItemStatus,
    preparationTime: 5,
    destination: 'kitchen',
    allergens: ['gluten', 'lácteos', 'huevo'],
    isVegetarian: true,
    isPopular: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

// ==================== MESAS ====================

export const mockTables: Table[] = Array.from({ length: 24 }, (_, i) => {
  const tableNumber = i + 1;
  const status = i < 6 ? 'available' : i < 18 ? 'occupied' : i < 21 ? 'reserved' : 'cleaning';
  
  return {
    id: `table-${tableNumber}`,
    number: tableNumber,
    capacity: tableNumber % 6 === 0 ? 8 : tableNumber % 4 === 0 ? 6 : tableNumber % 2 === 0 ? 4 : 2,
    status: status as TableStatus,
    currentSession: status === 'occupied' ? `session-${tableNumber}` : undefined,
    assignedWaiter: status === 'occupied' ? `waiter-${(i % 3) + 1}` : undefined,
    zone: `Zona ${String.fromCharCode(65 + Math.floor(i / 6))}`, // A, B, C, D
    positionX: (i % 6) * 150 + 50,
    positionY: Math.floor(i / 6) * 150 + 50,
    qrCode: `QR-TABLE-${tableNumber}`,
  };
});

// ==================== USUARIOS ====================

export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'admin',
    email: 'admin@smartmenu.com',
    fullName: 'María García',
    role: 'admin' as UserRole,
    isActive: true,
    phone: '+1 809-555-0101',
    avatar: '/avatars/admin.jpg',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    username: 'carlos.mesero',
    email: 'carlos@smartmenu.com',
    fullName: 'Carlos Rodríguez',
    role: 'waiter' as UserRole,
    isActive: true,
    phone: '+1 809-555-0102',
    assignedZone: 'Zona A',
    pin: '1234',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'user-3',
    username: 'ana.mesera',
    email: 'ana@smartmenu.com',
    fullName: 'Ana Martínez',
    role: 'waiter' as UserRole,
    isActive: true,
    phone: '+1 809-555-0103',
    assignedZone: 'Zona B',
    pin: '5678',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'user-4',
    username: 'chef.pedro',
    email: 'pedro@smartmenu.com',
    fullName: 'Pedro Sánchez',
    role: 'chef' as UserRole,
    isActive: true,
    phone: '+1 809-555-0104',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'user-5',
    username: 'bartender.luis',
    email: 'luis@smartmenu.com',
    fullName: 'Luis Fernández',
    role: 'bartender' as UserRole,
    isActive: true,
    phone: '+1 809-555-0105',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
];

// ==================== ÓRDENES ====================

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 1001,
    tableId: 'table-5',
    tableNumber: 5,
    sessionId: 'session-5',
    items: [
      {
        id: 'item-1-1',
        menuItem: mockMenuItems[0],
        quantity: 2,
        unitPrice: 185,
        totalPrice: 370,
        status: 'preparing',
        notes: 'Sin cebolla',
        allergies: ['LÁCTEOS'],
        hasAllergies: true,
        createdAt: new Date(Date.now() - 15 * 60 * 1000),
      },
      {
        id: 'item-1-2',
        menuItem: mockMenuItems[3],
        quantity: 1,
        unitPrice: 485,
        totalPrice: 485,
        notes: 'Término 3/4',
        allergies: ['GLUTEN'],
        hasAllergies: true,
        specialInstructions: 'Sin mantequilla en la preparación',
        status: 'preparing',
        createdAt: new Date(Date.now() - 15 * 60 * 1000),
      },
      {
        id: 'item-1-3',
        menuItem: mockMenuItems[8],
        quantity: 2,
        unitPrice: 135,
        totalPrice: 270,
        status: 'ready',
        createdAt: new Date(Date.now() - 15 * 60 * 1000),
        completedAt: new Date(Date.now() - 5 * 60 * 1000),
      },
    ],
    subtotal: 1125,
    tax: 180,
    total: 1305,
    status: 'preparing' as OrderStatus,
    waiterId: 'user-2',
    waiterName: 'Carlos Rodríguez',
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: 'order-2',
    orderNumber: 1002,
    tableId: 'table-9',
    tableNumber: 9,
    sessionId: 'session-9',
    items: [
      {
        id: 'item-2-1',
        menuItem: mockMenuItems[1],
        quantity: 1,
        unitPrice: 245,
        totalPrice: 245,
        allergies: ['mariscos', 'ajo'],
        specialInstructions: 'Cliente muy alérgico - usar utensilios limpios',
        status: 'ready',
        createdAt: new Date(Date.now() - 25 * 60 * 1000),
        completedAt: new Date(Date.now() - 10 * 60 * 1000),
      },
      {
        id: 'item-2-2',
        menuItem: mockMenuItems[5],
        quantity: 1,
        unitPrice: 395,
        totalPrice: 395,
        status: 'ready',
        createdAt: new Date(Date.now() - 25 * 60 * 1000),
        completedAt: new Date(Date.now() - 10 * 60 * 1000),
      },
    ],
    subtotal: 640,
    tax: 102,
    total: 742,
    status: 'ready' as OrderStatus,
    waiterId: 'user-2',
    waiterName: 'Carlos Rodríguez',
    createdAt: new Date(Date.now() - 25 * 60 * 1000),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000),
  },
  {
    id: 'order-3',
    orderNumber: 1003,
    tableId: 'table-12',
    tableNumber: 12,
    sessionId: 'session-12',
    items: [
      {
        id: 'item-3-1',
        menuItem: mockMenuItems[6],
        quantity: 3,
        unitPrice: 235,
        totalPrice: 705,
        notes: 'Extra queso',
        allergies: ['nueces'],
        status: 'preparing',
        createdAt: new Date(Date.now() - 10 * 60 * 1000),
      },
      {
        id: 'item-3-2',
        menuItem: mockMenuItems[10],
        quantity: 3,
        unitPrice: 65,
        totalPrice: 195,
        status: 'ready',
        createdAt: new Date(Date.now() - 10 * 60 * 1000),
        completedAt: new Date(Date.now() - 8 * 60 * 1000),
      },
    ],
    subtotal: 900,
    tax: 144,
    total: 1044,
    status: 'preparing' as OrderStatus,
    waiterId: 'user-3',
    waiterName: 'Ana Martínez',
    createdAt: new Date(Date.now() - 18 * 60 * 1000),
    updatedAt: new Date(Date.now() - 18 * 60 * 1000),
  },
  {
    id: 'order-4',
    orderNumber: 1004,
    tableId: 'table-9',
    tableNumber: 9,
    sessionId: 'session-9',
    items: [
      {
        id: 'item-4-1',
        menuItem: {...mockMenuItems[4], name: 'Tacos de Arrachera'},
        quantity: 3,
        unitPrice: 185,
        totalPrice: 555,
        status: 'preparing',
        notes: 'Con salsa verde',
        createdAt: new Date(Date.now() - 6 * 60 * 1000),
      },
    ],
    subtotal: 555,
    tax: 89,
    total: 644,
    status: 'preparing' as OrderStatus,
    waiterId: 'user-2',
    waiterName: 'Carlos Rodríguez',
    createdAt: new Date(Date.now() - 6 * 60 * 1000),
    updatedAt: new Date(Date.now() - 6 * 60 * 1000),
  },
  {
    id: 'order-5',
    orderNumber: 1005,
    tableId: 'table-2',
    tableNumber: 2,
    sessionId: 'session-2',
    items: [
      {
        id: 'item-5-1',
        menuItem: {...mockMenuItems[4], name: 'Hamburguesa Gourmet'},
        quantity: 2,
        unitPrice: 285,
        totalPrice: 570,
        status: 'preparing',
        notes: 'Sin cebolla',
        allergies: ['GLUTEN'],
        hasAllergies: true,
        createdAt: new Date(Date.now() - 5 * 60 * 1000),
      },
    ],
    subtotal: 570,
    tax: 91,
    total: 661,
    status: 'preparing' as OrderStatus,
    waiterId: 'user-3',
    waiterName: 'Ana Martínez',
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000),
  },
];

// Helper functions
export function getElapsedMinutes(date: Date): number {
  return Math.floor((Date.now() - date.getTime()) / (1000 * 60));
}

export function generateMockOrder(tableNumber: number): Order {
  const randomItems = Array.from({ length: Math.floor(Math.random() * 3) + 1 }, () => {
    const item = mockMenuItems[Math.floor(Math.random() * mockMenuItems.length)];
    const quantity = Math.floor(Math.random() * 2) + 1;
    return {
      id: `item-${Date.now()}-${Math.random()}`,
      menuItem: item,
      quantity,
      unitPrice: item.price,
      totalPrice: item.price * quantity,
      status: 'pending' as OrderItemStatus,
      createdAt: new Date(),
    };
  });

  const subtotal = randomItems.reduce((sum, item) => sum + item.totalPrice, 0);
  const tax = Math.round(subtotal * 0.16);
  
  return {
    id: `order-${Date.now()}`,
    orderNumber: Math.floor(Math.random() * 9000) + 1000,
    tableId: `table-${tableNumber}`,
    tableNumber,
    sessionId: `session-${tableNumber}`,
    items: randomItems,
    subtotal,
    tax,
    total: subtotal + tax,
    status: 'pending' as OrderStatus,
    waiterId: mockUsers[Math.floor(Math.random() * 3) + 1].id,
    waiterName: mockUsers[Math.floor(Math.random() * 3) + 1].fullName,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}
